#
# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: GPL v2.0
#
# Licensed under the GNU Lesser General Public License version 2 (the "License");
# you may not use this file except in compliance with the License. The terms
# of the License are located in the LICENSE file of this distribution.
#

INCLUDE = -I../include
all:
	$(CC) -g $(INCLUDE) -o hmacgen hmacgen.c
clean:
	rm -f *.o
	rm -f hmacgen
